# Generated by Django 4.1.2 on 2022-10-23 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Druzyna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('kraj', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('data_dodania', models.DateField(auto_now_add=True)),
                ('Drużyna', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.druzyna')),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
    ]
