# Generated by Django 4.1.2 on 2022-11-23 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_persons_miesiac_urodzenia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('miesiac_urodzenia', models.IntegerField(choices=[(1, 'Styczeń'), (2, 'Luty'), (3, 'Marzec'), (4, 'Kwiecień'), (5, 'Maj'), (6, 'Czerwiec'), (7, 'Lipiec'), (8, 'Sierpień'), (9, 'Wrzesień'), (10, 'Październik'), (11, 'Listopad'), (12, 'Grudzień')], default='1')),
                ('data_dodania', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nazwisko'],
            },
        ),
        migrations.RenameModel(
            old_name='Druzyna',
            new_name='Team',
        ),
        migrations.DeleteModel(
            name='Persons',
        ),
        migrations.AddField(
            model_name='person',
            name='Drużyna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.team'),
        ),
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL),
        ),
    ]
